name = "CessiStommel_DS"
uuid = "7bab67e1-837e-429f-923e-7056d7840936"
authors = ["Daniel Pals <Daniel.Pals@tum.de>"]
version = "1.0.0-DEV"

[compat]
julia = "1.8.5"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
